# Climate Data Analysis Project
This notebook analyzes daily temperature and humidity data from 500 locations for a year.
Each task is organized into a section for easier review and understanding.

# Task 1 initialize Temperature and Humidity Data 
Set up two arrays to represent daily data: 
• temperature_data: Randomly generated temperature values in 
Celsius, ranging between -10 and 40 degrees, for each of the 500 locations 
across 365 days. 
• humidity_data: Randomly generated humidity percentages, ranging 
from 0 to 100, for each location and day.

In [3]:
import numpy as np
# Task 1: Initialize Temperature and Humidity Data
# Generate random data for temperature (in Celsius) and humidity (in percentage) for each day of the year.
temperature_data = np.random.uniform(-10, 40, (500, 365))
humidity_data = np.random.uniform(0, 100, (500, 365))

# Output first few rows to check data.
temperature_data[:5, :5], humidity_data[:5, :5]

(array([[30.22208988,  6.61811043, -2.47282254, -2.61371605, 12.70609906],
        [38.80256258, -0.0640887 , 26.67336616, -2.81630719, 29.67972257],
        [25.19210595, -4.45628049, 14.93372309, 38.86893319, 30.92970933],
        [12.52480228,  0.84598489, -7.72494185,  7.57490926, 11.74669206],
        [30.93131563, 29.74419696, 34.9183831 , -0.80429642, 18.3770796 ]]),
 array([[ 8.69402456, 89.72210708, 28.46180077, 90.68803567, 77.58944148],
        [79.76650028, 31.13992629, 15.39825105, 39.72681607,  7.96221313],
        [98.92153102, 58.48027888, 69.13132533, 98.8579108 , 54.12636625],
        [46.60064918, 77.7462611 , 43.46155451,  8.28834463, 98.36166781],
        [74.88841013, 45.54209366, 84.23318378, 95.57519917, 25.8161521 ]]))

In [4]:
# Task 2: Simulate Missing Data
# Randomly set 5% of values to NaN to simulate missing data.
import numpy as np

temperature_missing_mask = np.random.rand(500, 365) < 0.05
humidity_missing_mask = np.random.rand(500, 365) < 0.05
temperature_data[temperature_missing_mask] = np.nan
humidity_data[humidity_missing_mask] = np.nan

# Count and print the number of NaNs in each dataset.
temperature_missing_count = np.isnan(temperature_data).sum()
humidity_missing_count = np.isnan(humidity_data).sum()
temperature_missing_count, humidity_missing_count

(9173, 9188)

In [5]:
# Task 3: Convert Temperature to Fahrenheit and Calculate Discomfort Index
# Convert Celsius to Fahrenheit.
temperature_data_fahrenheit = (temperature_data * 9/5) + 32

# Calculate feels-like index based on temperature and humidity.
feels_like_index = (temperature_data_fahrenheit + (humidity_data / 2))

# Cap values at 80 in feels_like_index.
feels_like_index[feels_like_index > 80] = 80

# Preview result.
feels_like_index[:5, :5]

array([[80.        , 80.        , 41.77981981, 72.63932894, 80.        ],
       [80.        , 47.45460349, 80.        , 46.79405509, 80.        ],
       [80.        , 53.21883456, 80.        , 80.        , 80.        ],
       [77.84496869, 72.39590336, 39.82588193, 49.77900898, 80.        ],
       [80.        , 80.        , 80.        , 78.33986603, 77.98681934]])